### ISSUE TITLE
Dynamic class names changed to `[object Object]`

### ISSUE THREAD

**Issue by archonic** [testdouble/vscode-standard-ruby#6]
I noticed the same thing using @prettier/plugin-ruby.

This:
```
<div class="<%= dynamic_class %>">...</div>
```

Is formatting to this:
```
<div class="[object Object]">...</div>
```

**Comment by searls** [comment]
Huh, that's interesting. Was this in an `erb` file? Could you share a sample file listing?

**Comment by archonic** [comment]
I think I might have had prettier/plugin-ruby still present. I tried creating a minimal reproduction and this extension isn't formatting ERB at all. Is this extension meant to have any handling of erb files?

**Comment by searls** [comment]
Correct, rubocop and standard do not format or lint ERB files in fact

**Comment by archonic** [comment]
Ok, that explains it. I would love it if they did. Closing!
